@httpAddress = http://0.0.0.0:8080
@httpsAddress = https://0.0.0.0:7098
@deployedAddress = https://src.ambitiousdesert-52c4453d.eastus2.azurecontainerapps.io

### 
GET {{httpAddress}}/
Accept: application/json

###
# @name authorizeLocal
Get https://0.0.0.0:7098/authorize?client_id=BYNoOlaf3vqx868Z8tJWRTu5&redirect_uri=https://0.0.0.0:7098/dummyRedirect&response_type=code&code_challenge_method=S256&code_challenge=test&resource=http://test.com

###
# @name authorizeDeployed
Get https://src.ambitiousdesert-52c4453d.eastus2.azurecontainerapps.io/authorize?client_id=aO7hdQ700YCvEZ5TTWwRDn03&redirect_uri=https://src.ambitiousdesert-52c4453d.eastus2.azurecontainerapps.io/dummyRedirect&response_type=code&code_challenge_method=S256&code_challenge=test&resource=http://test.com

### 
### 
# @name registerClient
POST {{deployedAddress}}/register
Content-Type: application/json
Accept: application/json

{"redirect_uris":["https://chatgpt.com/connector_platform_oauth_redirect"],"client_name":"ChatGPT","token_endpoint_auth_method":"none","grant_types":["authorization_code","refresh_token"],"response_types":["code"],"scope":null}


### 

### Test GetClient
GET {{deployedAddress}}/register/{{registerClient.response.body.client_id}}
Accept: application/json
Authorization: Bearer {{registerClient.response.body.registration_access_token}}
Connection: keep-alive
###

### 
# @name tokenLocal
POST {{deployedAddress}}/token
Content-Type: application/json
Accept: application/json

{
    "code": "VNCBMM48igOE67Y7hPdgTAQtOD6flh4aiyy9iRyd2fU",
    "code_verifier": "test",
    "grant_type": "authorization_code"
}

### 