@src_HostAddress = http://localhost:5296

GET {{src_HostAddress}}/
Accept: application/json

###
Get https://0.0.0.0:7029/authorize?client_id=123&redirect_uri=https://0.0.0.0:7029/test&response_type=code&code_challenge_method=S256&code_challenge=test&resource=http://test.com


### deployed app
GET https://src.ambitiousdesert-52c4453d.eastus2.azurecontainerapps.io/authorize?client_id=123&redirect_uri=https://src.ambitiousdesert-52c4453d.eastus2.azurecontainerapps.io/dummyRedirect&response_type=code&code_challenge_method=S256&code_challenge=test&resource=http://test.com